# Generated by Django 6.1.1 on 2026-09-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='maximum_cost',
            new_name='max_cost',
        ),
        migrations.RenameField(
            model_name='treatment',
            old_name='minimum_cost',
            new_name='min_cost',
        ),
        migrations.AddField(
            model_name='treatment',
            name='patients_treated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='treatment',
            name='success_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='description',
            field=models.TextField(),
        ),
    ]
