# Generated by Django 6.1.1 on 2026-09-22 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_rename_maximum_cost_treatment_max_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='maps_link',
        ),
    ]
