# Generated by Django 6.1.1 on 2026-09-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_hospital_area_hospital_latitude_hospital_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='image_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
